local reflection = require "reflection"
local findCurrentHostFiber = reflection.findCurrentHostFiber
local findCurrentHostFiberWithNoPortals = reflection.findCurrentHostFiberWithNoPortals
local ReactInstanceMap = require "ReactInstanceMap"
local ReactTypeOfWork = require "ReactTypeOfWork"
local HostComponent = ReactTypeOfWork.HostComponent
local emptyObject = require "emptyObject"
local getComponentName = require "getComponentName"
local invariant = require "invariant"
local warning = require "warning"

local ReactFiberRoot = require "ReactFiberRoot"
local createFiberRoot = ReactFiberRoot.createFiberRoot
local ReactFiberDevToolsHook = require "ReactFiberDevToolsHook"
local ReactFiberScheduler = require "ReactFiberScheduler"
local ReactFiberUpdateQueue = require "ReactFiberUpdateQueue"
local insertUpdateIntoFiber = ReactFiberUpdateQueue.insertUpdateIntoFiber
local ReactFiberInstrumentation = require "ReactFiberInstrumentation"
local ReactDebugCurrentFiber = require "ReactDebugCurrentFiber"